name: 'Refresh extensions translations with crowdin'
on:
  push:
    paths:
      - 'extensions/*/locales/source/extension.json'
  workflow_dispatch:  # click the button on Github repo!

jobs:
  crowdin_extensions_refresh:
    name: 'Refresh with crowdin.com for extensions translations'
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout current branch
        uses: actions/checkout@v3
      - id: crowdin-refresh
        name: Refresh extensions translations
        uses: crowdin/github-action@1.5.1
        with:
          upload_sources: true
          upload_translations: true
          download_translations: true
          # Export options
          skip_untranslated_strings: true
          export_only_approved: true
          # git options
          push_translations: false
          config: '.crowdin.extensions.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
      - id: transform
        name: Transform and commit changes
        uses: PetroSVoronov/action-prepare-locales@v2.0.2
        with:
          source_translations_pattern: 'extensions/*/locales/source/extension_(??).json'
          transformed_translations_relative_path_and_pattern: '../locale_$language$.json'
          git_user_name: github-actions
          git_user_email: github-actions@github.com
      - id: push
        name: Push changes
        if: steps.transform.outputs.is_commit_available == 'true'
        run: |
          git push
